version: '3.4'

services:
  elasticsearch:
    build: ./elasticsearch/
    container_name: elasticsearch
    ports:
        - 9200:9200
        - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
        - ./.docker/elasticsearch/esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.10.1
    container_name: kibana
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"

  wizard:
    container_name: dashboard_wizard
    build: ./wizard
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "KIBANA_URL=http://kibana:5601"
    command: [ '/bin/bash', '-c', 'cat /tmp/sample/load-sample-data.sh | tr -d "\r" | bash' ]
    depends_on:
      - elasticsearch
      - kibana
