version: '3.4'

services:
  elasticsearch:
#    build: .
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    ports:
        - 9200:9200
        - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
        - ./.docker/elasticsearch/esdata:/usr/share/elasticsearch/data

  kibana:
    build: ./kibana/Dockerfile
    container_name: kibana
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"