version: '3.4'

services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    ports:
        - 9200:9200
        - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
        - ./.docker/elasticsearch/esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.10.1
    container_name: kibana
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"

  logstash:
    build: ./logstash
    container_name: logstash
    ports:
      - 5044:5044
      - 5000:5000/tcp
      - 5000:5000/udp
      - 9600:9600
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    command: logstash -f /tmp/logstash.conf

  wizard:
    container_name: dashboard_wizard
    build: ./wizard
    depends_on:
      - elasticsearch
      - kibana
      - logstash
